### ISSUE TITLE
Tracking issue for SPL

### ISSUE THREAD

**Issue by cruelbob** [peachpiecompiler/peachpie#270]
### Datastructures
- [x] [SplDoublyLinkedList](http://php.net/manual/en/class.spldoublylinkedlist.php)
- [x] [SplStack](http://php.net/manual/en/class.splstack.php)
- [x] [SplQueue](http://php.net/manual/en/class.splqueue.php)
- [x] [SplHeap](http://php.net/manual/en/class.splheap.php)
- [x] [SplMaxHeap](http://php.net/manual/en/class.splmaxheap.php)
- [x] [SplMinHeap](http://php.net/manual/en/class.splminheap.php)
- [x] [SplPriorityQueue](http://php.net/manual/en/class.splpriorityqueue.php)
- [x] [SplFixedArray](http://php.net/manual/en/class.splfixedarray.php)
- [x] [SplObjectStorage](http://php.net/manual/en/class.splobjectstorage.php)
### Iterators
- [x] [AppendIterator](http://php.net/manual/en/class.appenditerator.php)
- [x] [ArrayIterator](http://php.net/manual/en/class.arrayiterator.php)
- [x] [CachingIterator](http://php.net/manual/en/class.cachingiterator.php)
- [x] [CallbackFilterIterator](http://php.net/manual/en/class.callbackfilteriterator.php)
- [x] [DirectoryIterator](http://php.net/manual/en/class.directoryiterator.php)
- [x] [EmptyIterator](http://php.net/manual/en/class.emptyiterator.php)
- [x] [FilesystemIterator](http://php.net/manual/en/class.filesystemiterator.php)
- [x] [FilterIterator](http://php.net/manual/en/class.filteriterator.php)
- [x] [GlobIterator](http://php.net/manual/en/class.globiterator.php)
- [x] [InfiniteIterator](http://php.net/manual/en/class.infiniteiterator.php)
- [x] [IteratorIterator](http://php.net/manual/en/class.iteratoriterator.php)
- [x] [LimitIterator](http://php.net/manual/en/class.limititerator.php)
- [x] [MultipleIterator](http://php.net/manual/en/class.multipleiterator.php)
- [x] [NoRewindIterator](http://php.net/manual/en/class.norewinditerator.php)
- [x] [ParentIterator](http://php.net/manual/en/class.parentiterator.php)
- [x] [RecursiveArrayIterator](http://php.net/manual/en/class.recursivearrayiterator.php)
- [x] [RecursiveCachingIterator](http://php.net/manual/en/class.recursivecachingiterator.php)
- [x] [RecursiveCallbackFilterIterator](http://php.net/manual/en/class.recursivecallbackfilteriterator.php)
- [x] [RecursiveDirectoryIterator](http://php.net/manual/en/class.recursivedirectoryiterator.php)
- [x] [RecursiveFilterIterator](http://php.net/manual/en/class.recursivefilteriterator.php)
- [x] [RecursiveIteratorIterator](http://php.net/manual/en/class.recursiveiteratoriterator.php)
- [x] [RecursiveRegexIterator](http://php.net/manual/en/class.recursiveregexiterator.php)
- [x] [RecursiveTreeIterator](http://php.net/manual/en/class.recursivetreeiterator.php)
- [x] [RegexIterator](http://php.net/manual/en/class.regexiterator.php)
### Interfaces
- [x] [Countable](http://php.net/manual/en/class.countable.php)
- [x] [OuterIterator](http://php.net/manual/en/class.outeriterator.php)
- [x] [RecursiveIterator](http://php.net/manual/en/class.recursiveiterator.php)
- [x] [SeekableIterator](http://php.net/manual/en/class.seekableiterator.php)
### Exceptions
- [x] [BadFunctionCallException](http://php.net/manual/en/class.badfunctioncallexception.php)
- [x] [BadMethodCallException](http://php.net/manual/en/class.badmethodcallexception.php)
- [x] [DomainException](http://php.net/manual/en/class.domainexception.php)
- [x] [InvalidArgumentException](http://php.net/manual/en/class.invalidargumentexception.php)
- [x] [LengthException](http://php.net/manual/en/class.lengthexception.php)
- [x] [LogicException](http://php.net/manual/en/class.logicexception.php)
- [x] [OutOfBoundsException](http://php.net/manual/en/class.outofboundsexception.php)
- [x] [OutOfRangeException](http://php.net/manual/en/class.outofrangeexception.php)
- [x] [OverflowException](http://php.net/manual/en/class.overflowexception.php)
- [x] [RangeException](http://php.net/manual/en/class.rangeexception.php)
- [x] [RuntimeException](http://php.net/manual/en/class.runtimeexception.php)
- [x] [UnderflowException](http://php.net/manual/en/class.underflowexception.php)
- [x] [UnexpectedValueException](http://php.net/manual/en/class.unexpectedvalueexception.php)
### SPL Functions
- [x] [class_implements](http://php.net/manual/en/function.class-implements.php)
- [x] [class_parents](http://php.net/manual/en/function.class-parents.php)
- [x] [class_uses](http://php.net/manual/en/function.class-uses.php)
- [x] [iterator_apply](http://php.net/manual/en/function.iterator-apply.php)
- [x] [iterator_count](http://php.net/manual/en/function.iterator-count.php)
- [x] [iterator_to_array](http://php.net/manual/en/function.iterator-to-array.php)
- [x] [spl_autoload_call](http://php.net/manual/en/function.spl-autoload-call.php)
- [x] [spl_autoload_extensions](http://php.net/manual/en/function.spl-autoload-extensions.php)
- [x] [spl_autoload_functions](http://php.net/manual/en/function.spl-autoload-functions.php)
- [x] [spl_autoload_register](http://php.net/manual/en/function.spl-autoload-register.php)
- [x] [spl_autoload_unregister](http://php.net/manual/en/function.spl-autoload-unregister.php)
- [x] [spl_autoload](http://php.net/manual/en/function.spl-autoload.php)
- [x] [spl_classes](http://php.net/manual/en/function.spl-classes.php)
- [x] [spl_object_hash](http://php.net/manual/en/function.spl-object-hash.php)
- [x] [spl_object_id](http://php.net/manual/en/function.spl-object-id.php)
### File Handling
- [x] [SplFileInfo](http://php.net/manual/en/class.splfileinfo.php)
- [x] [SplFileObject](http://php.net/manual/en/class.splfileobject.php)
- [x] [SplTempFileObject](http://php.net/manual/en/class.spltempfileobject.php)
### Miscellaneous Classes and Interfaces
- [x] [ArrayObject](http://php.net/manual/en/class.arrayobject.php)
- [x] [SplObserver](http://php.net/manual/en/class.splobserver.php)
- [x] [SplSubject](http://php.net/manual/en/class.splsubject.php)

**Comment by bfistein** [comment]
Thanks @cruelbob for this great tracking issue and @roberthusak for implementing the missing ones. Should mostly be done now @cruelbob, closing this.
