### ISSUE TITLE
Remaining issues when trying to port a woocommerce site

### ISSUE THREAD

**Issue by Valks** [peachpiecompiler/peachpie#704]
Below is a list of plugins and errors during compile time.

- amazon-s3-and-cloudfront		- Dependency of another plugin:

- [x] #604 ```wp-content/plugins/amazon-s3-and-cloudfront/vendor/Gcp/google/cloud-core/src/GrpcRequestWrapper.php(156,18): error PHP4042: Yielding from an exception handling construct (try, catch, finally) is currently not supported by PeachPie. [/src/Plugins/AmazonS3andCloudfront/AmazonS3andCloudfront.msbuildproj]```
- [x] #604 ```wp-content/plugins/amazon-s3-and-cloudfront/vendor/Aws3/Aws/S3/S3MultiRegionClient.php(225,26): error PHP4042: Yielding from an exception handling construct (try, catch, finally) is currently not supported by PeachPie. [/src/Plugins/AmazonS3andCloudfront/AmazonS3andCloudfront.msbuildproj]```
- [x] #604 ```wp-content/plugins/amazon-s3-and-cloudfront/vendor/Aws3/Aws/S3/S3MultiRegionClient.php(239,26): error PHP4042: Yielding from an exception handling construct (try, catch, finally) is currently not supported by PeachPie. [/src/Plugins/AmazonS3andCloudfront/AmazonS3andCloudfront.msbuildproj]```
- [x] #604 ```wp-content/plugins/amazon-s3-and-cloudfront/vendor/Aws3/Aws/S3/S3MultiRegionClient.php(236,40): error PHP4042: Yielding from an exception handling construct (try, catch, finally) is currently not supported by PeachPie. [/src/Plugins/AmazonS3andCloudfront/AmazonS3andCloudfront.msbuildproj]```
- [x] #604 ```wp-content/plugins/amazon-s3-and-cloudfront/vendor/Aws3/Aws/S3/S3MultiRegionClient.php(246,34): error PHP4042: Yielding from an exception handling construct (try, catch, finally) is currently not supported by PeachPie. [/src/Plugins/AmazonS3andCloudfront/AmazonS3andCloudfront.msbuildproj]```
- [x] #604 ```wp-content/plugins/amazon-s3-and-cloudfront/vendor/Aws3/Aws/Waiter.php(78,32): error PHP4042: Yielding from an exception handling construct (try, catch, finally) is currently not supported by PeachPie. [/src/Plugins/AmazonS3andCloudfront/AmazonS3andCloudfront.msbuildproj]```
- [ ] ``` wp-content/plugins/amazon-s3-and-cloudfront/vendor/Aws3/Aws/DoctrineCacheAdapter.php(6,98): error PHP4044: Type name 'DeliciousBrains\WP_Offload_Media\Aws3\Doctrine\Common\Cache\Cache' could not be resolved. [/src/Plugins/AmazonS3andCloudfront/AmazonS3andCloudfront.msbuildproj]```
- [ ] ``` wp-content/plugins/amazon-s3-and-cloudfront/vendor/Aws3/Aws/Handler/GuzzleV5/GuzzleStream.php(13,31): error PHP4044: Type name 'DeliciousBrains\WP_Offload_Media\Aws3\GuzzleHttp\Stream\StreamInterface' could not be resolved. [/src/Plugins/AmazonS3andCloudfront/AmazonS3andCloudfront.msbuildproj]```
- [ ] ``` wp-content/plugins/amazon-s3-and-cloudfront/vendor/Aws3/Aws/Handler/GuzzleV5/GuzzleStream.php(15,9): error PHP4044: Type name 'DeliciousBrains\WP_Offload_Media\Aws3\GuzzleHttp\Stream\StreamDecoratorTrait' could not be resolved. [/src/Plugins/AmazonS3andCloudfront/AmazonS3andCloudfront.msbuildproj]```
- [ ] ``` wp-content/plugins/amazon-s3-and-cloudfront/vendor/Aws3/Aws/Handler/GuzzleV5/PsrStream.php(15,9): error PHP4044: Type name 'DeliciousBrains\WP_Offload_Media\Aws3\GuzzleHttp\Stream\StreamDecoratorTrait' could not be resolved. [/src/Plugins/AmazonS3andCloudfront/AmazonS3andCloudfront.msbuildproj]```
- [ ] ``` wp-content/plugins/amazon-s3-and-cloudfront/vendor/Gcp/google/auth/src/Subscriber/AuthTokenSubscriber.php(35,38): error PHP4044: Type name 'DeliciousBrains\WP_Offload_Media\Gcp\GuzzleHttp\Event\SubscriberInterface' could not be resolved. [/src/Plugins/AmazonS3andCloudfront/AmazonS3andCloudfront.msbuildproj]```
- [ ] ``` wp-content/plugins/amazon-s3-and-cloudfront/vendor/Gcp/google/auth/src/Subscriber/ScopedAccessTokenSubscriber.php(37,46): error PHP4044: Type name 'DeliciousBrains\WP_Offload_Media\Gcp\GuzzleHttp\Event\SubscriberInterface' could not be resolved. [/src/Plugins/AmazonS3andCloudfront/AmazonS3andCloudfront.msbuildproj]```
- [ ] ``` wp-content/plugins/amazon-s3-and-cloudfront/vendor/Gcp/google/auth/src/Subscriber/SimpleSubscriber.php(29,35): error PHP4044: Type name 'DeliciousBrains\WP_Offload_Media\Gcp\GuzzleHttp\Event\SubscriberInterface' could not be resolved. [/src/Plugins/AmazonS3andCloudfront/AmazonS3andCloudfront.msbuildproj]```
- [ ] ``` wp-content/plugins/amazon-s3-and-cloudfront/vendor/Gcp/google/cloud-core/src/PhpArray.php(31,24): error PHP4044: Type name 'DeliciousBrains\WP_Offload_Media\Gcp\DrSlump\Protobuf\Codec\PhpArray' could not be resolved. [/src/Plugins/AmazonS3andCloudfront/AmazonS3andCloudfront.msbuildproj]```

- woocommerce google analytics pro	- Bought Premium Plugin:

- [ ] ``` wp-content/plugins/woocommerce-google-analytics-pro/includes/api/class-wc-google-analytics-pro-measurement-protocol-api-request.php(108,10): error PHP2070: Cannot access parent:: when current class scope has no parent [/src/Plugins/WooCommerceGoogleAnalyticsPro/WooCommerceGoogleAnalyticsPro.msbuildproj]```
- [ ] ``` wp-content/plugins/woocommerce-google-analytics-pro/includes/api/class-wc-google-analytics-pro-measurement-protocol-api-request.php(95,10): error PHP2070: Cannot access parent:: when current class scope has no parent [/src/Plugins/WooCommerceGoogleAnalyticsPro/WooCommerceGoogleAnalyticsPro.msbuildproj]```

- YoastSeoPremium				- Bought Premium Plugin:

- [ ] ``` wp-content/plugins/wordpress-seo-premium/vendor_prefixed/guzzlehttp/promises/src/functions.php(201,12): error PHP4046: Call to a member function then() on array|boolean [/src/Plugins/WordpressSeoPremium/WordpressSeoPremium.msbuildproj]```
- [ ] ``` wp-content/plugins/wordpress-seo-premium/vendor_prefixed/guzzlehttp/promises/src/functions.php(276,12): error PHP4046: Call to a member function then() on array|boolean [/src/Plugins/WordpressSeoPremium/WordpressSeoPremium.msbuildproj]```
- [ ] ``` wp-content/plugins/wordpress-seo-premium/vendor_prefixed/guzzlehttp/promises/src/functions.php(230,12): error PHP4046: Call to a member function then() on array|boolean [/src/Plugins/WordpressSeoPremium/WordpressSeoPremium.msbuildproj]```
- [ ] ``` wp-content/plugins/wordpress-seo-premium/cli/class-cli-redirect-upsell-command-namespace.php(13,65): error PHP4044: Type name 'WP_CLI\Dispatcher\CommandNamespace' could not be resolved. [/src/Plugins/WordpressSeoPremium/WordpressSeoPremium.msbuildproj]```
- [ ] ``` wp-content/plugins/wordpress-seo-premium/cli/class-cli-yoast-command-namespace.php(13,55): error PHP4044: Type name 'WP_CLI\Dispatcher\CommandNamespace' could not be resolved. [/src/Plugins/WordpressSeoPremium/WordpressSeoPremium.msbuildproj]```
- [ ] ``` wp-content/plugins/wordpress-seo-premium/config/dependency-injection/custom-loader.php(22,29): error PHP4044: Type name 'Symfony\Component\DependencyInjection\Loader\PhpFileLoader' could not be resolved. [/src/Plugins/WordpressSeoPremium/WordpressSeoPremium.msbuildproj]```
- [ ] ``` wp-content/plugins/wordpress-seo-premium/config/dependency-injection/loader-pass.php(25,30): error PHP4044: Type name 'Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface' could not be resolved. [/src/Plugins/WordpressSeoPremium/WordpressSeoPremium.msbuildproj]```
- [ ] ``` wp-content/plugins/wordpress-seo-premium/config/php-codeshift/remove-vendor-prefixing-array-key-visitor.php(18,57): error PHP4044: Type name 'PhpParser\NodeVisitorAbstract' could not be resolved. [/src/Plugins/WordpressSeoPremium/WordpressSeoPremium.msbuildproj]```
- [ ] ``` wp-content/plugins/wordpress-seo-premium/config/php-codeshift/remove-vendor-prefixing-codemod.php(15,47): error PHP4044: Type name 'Codeshift\AbstractCodemod' could not be resolved. [/src/Plugins/WordpressSeoPremium/WordpressSeoPremium.msbuildproj]```
- [ ] ``` wp-content/plugins/wordpress-seo-premium/config/php-codeshift/remove-vendor-prefixing-comment-visitor.php(17,55): error PHP4044: Type name 'PhpParser\NodeVisitorAbstract' could not be resolved. [/src/Plugins/WordpressSeoPremium/WordpressSeoPremium.msbuildproj]```
- [ ] ``` wp-content/plugins/wordpress-seo-premium/config/php-codeshift/remove-vendor-prefixing-visitor.php(17,47): error PHP4044: Type name 'PhpParser\NodeVisitorAbstract' could not be resolved. [/src/Plugins/WordpressSeoPremium/WordpressSeoPremium.msbuildproj]```
- [ ] ``` wp-content/plugins/wordpress-seo-premium/premium/cli/cli-redirect-command-namespace.php(13,58): error PHP4044: Type name 'WP_CLI\Dispatcher\CommandNamespace' could not be resolved. [/src/Plugins/WordpressSeoPremium/WordpressSeoPremium.msbuildproj]```

- Yith WooCommerce Gift Cards Premium	- Bought Premium Plugin:

- [ ] ``` wp-content/plugins/yith-woocommerce-gift-cards-premium/lib/vendor/setasign/fpdi/src/FpdfTpl.php(19,23): error PHP4044: Type name 'FPDF' could not be resolved. [/src/Plugins/YithWooCommerceGiftCardsPremium/YithWooCommerceGiftCardsPremium.msbuildproj]```
- [ ] ``` wp-content/plugins/yith-woocommerce-gift-cards-premium/lib/vendor/setasign/fpdi/src/Tcpdf/Fpdi.php(25,20): error PHP4044: Type name 'TCPDF' could not be resolved. [/src/Plugins/YithWooCommerceGiftCardsPremium/YithWooCommerceGiftCardsPremium.msbuildproj]```
- [ ] ``` wp-content/plugins/yith-woocommerce-gift-cards-premium/lib/vendor/setasign/fpdi/src/Tfpdf/FpdfTpl.php(21,23): error PHP4044: Type name 'tFPDF' could not be resolved. [/src/Plugins/YithWooCommerceGiftCardsPremium/YithWooCommerceGiftCardsPremium.msbuildproj]```

- Yoast WooCommerce SEO			- Bought Premium Plugin:
  - Depends on YoastSeoPremium

- NextgenGallery				- Free:
  - (Windows) File path limitations. Currently used to remove warnings in another plugin that depends on it (not actually used).

**Comment by jakubmisek** [comment]
**`PHP4046`** seams like a bug in the code, the error `PHP4046` is correct:
```php
\each()->then()
```
should be (as fixed on [github.com/guzzle/promises/src/functions.php:223](https://github.com/guzzle/promises/blob/89b1a76b7fda5853401297dc4b2a093cba1fda23/src/functions.php#L223))
```php
\GuzzleHttp\Promise\each()->then()
```

Yoast SEO should update its `\vendor_prefixed` folder. Or `\vendor_prefixed` might not be needed at all and can be excluded from the compilation?

**Comment by jakubmisek** [comment]
**`PHP4044`** is caused by compiling a class which depends on an optional WordPress component (mostly WP_CLI).

You can exclude `**/cli/**` from the `<Compile>` item group.

**Comment by jakubmisek** [comment]
@Valks `PHP2070` is usually a bug in the source code - can we see the source code of `class-wc-google-analytics-pro-measurement-protocol-api-request.php` - lines 107 - 110 ?

Probably the containing class does not have a parent at all, and the reported code would crash in runtime.

**Comment by dongfo** [comment]
PHP2070	Cannot access parent:: when current class scope has no parent	PhpShop	
it's  trait that cause this error.
use a trait without extend class

**Comment by Valks** [comment]
Going to close this issue as it's out of date, especially with the progress of peachpie.

@dongfo Thanks for pointing that out, I'll keep it in mind when I get back to this project.

**Comment by jakubmisek** [comment]
@dongfo thanks! this will be easy to fix

**Comment by dongfo** [comment]
@Valks @jakubmisek lately I figure it out ,It's my fault. the usage of trait is wrong in php. no need to fix.

**Comment by jakubmisek** [comment]
@dongfo ok, good, thank you :)
