### ISSUE TITLE
Missing tests tracking issue

### ISSUE THREAD

**Issue by jakubmisek** [peachpiecompiler/peachpie#752]
We have a bunch of features without being tested properly. Updated continuously.

- [ ] `include __DIR__ . "/subdir/file.php";` to get resolved in compile time. Add counter to `Context.Include(string)` to check it won't get called.
- [ ] recursions in call graph resulting in some blocks not being analyzed
- [ ] allow to compile "new Ns\Fn;" (not working in PHP7+, only with PeachPie)
- [ ] `$x->foo( $arr[$key] )` where `$arr` is `SplArrayObject`, `$key` is object`, $key must not be converted to IntStringKey
- [ ] CLR indexers (accessing Dictionary in foreach, [] setter, [] getter)
- [ ] json_encode() to reset json_last_error() to zero
- [ ] MySql functions
