### ISSUE TITLE
PHP 8 language support tracking issue

### ISSUE THREAD

**Issue by jakubmisek** [peachpiecompiler/peachpie#765]
- [ ] Union types
- [ ] Attributes 
- [ ] Constructor property promotion
- [ ] static return type
- [ ] mixed type
- [ ] Throw expression
- [ ] Weak maps
- [ ] Allowing ::class on objects
- [ ] Non-capturing catches
- [ ] Trailing comma in parameter lists
- [ ] DateTime objects from interface
- [ ] Stringable interface

features taken from https://stitcher.io/blog/new-in-php-8

BCL discussed separately
