### ISSUE TITLE
PHP 8.1 language support tracking issue

### ISSUE THREAD

**Issue by jakubmisek** [peachpiecompiler/peachpie#959]
**Configuration**

- [ ] LangVersion, /lang "8.1"

**Constructs**

- [ ] Enumerations (https://wiki.php.net/rfc/enumerations)
- [ ] Array unpacking with string keys (https://wiki.php.net/rfc/array_unpacking_string_keys)
- [ ] oct number notation (https://wiki.php.net/rfc/explicit_octal_notation)
- [ ] noreturn type (https://wiki.php.net/rfc/noreturn_type)
- [ ] static locals inheritance (https://wiki.php.net/rfc/static_variable_inheritance)

**Diagnostics**

- [ ] Restrict $GLOBALS usage (https://wiki.php.net/rfc/restrict_globals_usage)

**Library**

- [ ] array_is_list (https://wiki.php.net/rfc/is_list)
- [ ] fetch_column method to mysqli (https://wiki.php.net/rfc/mysqli_fetch_column)
- [ ] fsync (https://wiki.php.net/rfc/fsync_function)
- [ ] fibers (https://wiki.php.net/rfc/fibers)

**Comment by DRSDavidSoft** [comment]
@jakubmisek May I ask please for enums and readonly support?

I appreciate it! :thumbs_up:
